//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThietBi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThietBi
    {
        public int ID { get; set; }
        public int MaThietBi { get; set; }
        public int MaTinhTrang { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
    
        public virtual NguoiSuDung NguoiSuDung { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
